config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users
  resources :committees
  resources :categories
  resources :rules
  get 'rules/categories/:id' => 'rules#categories', as: :cats
  get 'rules/committees/:id' => 'rules#committees', as: :coms
  get 'old' => 'rules#old', as: :old
  
  root :to => 'rules#index'
resources :user_sessions
resources :users

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/committee.rb
class Committee < ActiveRecord::Base
  has_many :rules
  
  validates :name, presence: true
end

app/controllers/committees_controller.rb
class CommitteesController < ApplicationController
  before_action :set_committee, only: [:show, :edit, :update, :destroy]
    skip_before_action :require_login, only: [:index]
  # GET /committees
  # GET /committees.json
  def index
    @committees = Committee.all
  end

  # GET /committees/1
  # GET /committees/1.json
  def show
  end

  # GET /committees/new
  def new
    @committee = Committee.new
  end

  # GET /committees/1/edit
  def edit
  end

  # POST /committees
  # POST /committees.json
  def create
    @committee = Committee.new(committee_params)

    respond_to do |format|
      if @committee.save
        format.html { redirect_to committees_url, notice: 'Gremium erstellt.' }
        format.json { render :show, status: :created, location: @committee }
      else
        format.html { render :new }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /committees/1
  # PATCH/PUT /committees/1.json
  def update
    respond_to do |format|
      if @committee.update(committee_params)
        format.html { redirect_to committees_url, notice: 'Gremium aktualisiert.' }
        format.json { render :show, status: :ok, location: @committee }
      else
        format.html { render :edit }
        format.json { render json: @committee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /committees/1
  # DELETE /committees/1.json
  def destroy
    @committee.destroy
    respond_to do |format|
      format.html { redirect_to committees_url, notice: 'Gremium gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_committee
      @committee = Committee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def committee_params
      params.require(:committee).permit(:name)
    end
end

app/helpers/committees_helper.rb
module CommitteesHelper
end

app/views/committees/_form.html.erb
<%= form_for(@committee) do |f| %>
  <% if @committee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@committee.errors.count, "error") %> prohibited this committee from being saved:</h2>

      <ul>
      <% @committee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Speichern"%>
  </div>
<% end %>

app/views/committees/edit.html.erb
<h1>Editing Committee</h1>

<%= render 'form' %>

<%= link_to 'Show', @committee %> |
<%= link_to 'Back', committees_path %>

app/views/committees/index.html.erb
<p id="notice"><%= notice %></p>

<% @title= "Gremien" %>


<table class="table table-hover" id="index-table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @committees.each do |committee| %>
      <tr>
        <td><%= committee.name %></td>
        <td><%= link_to 'Show', committee %></td>
        <td><%= link_to 'Destroy', committee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Gremium erstellen', new_committee_path %>

app/views/committees/new.html.erb
<% @title= "Neues Gremium" %>

<%= render 'form' %>

<%= link_to 'Gremien anzeigen', committees_path %>

app/views/committees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @committee.name %>
</p>

<%= link_to 'Edit', edit_committee_path(@committee) %> |
<%= link_to 'Back', committees_path %>