config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users
  resources :committees
  resources :categories
  resources :rules
  get 'rules/categories/:id' => 'rules#categories', as: :cats
  get 'rules/committees/:id' => 'rules#committees', as: :coms
  get 'old' => 'rules#old', as: :old
  
  root :to => 'rules#index'
resources :user_sessions
resources :users

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/rule.rb
class Rule < ActiveRecord::Base
  has_many :line_items
  has_many :categories,through: :line_items
  belongs_to :committee

validates :title, presence: true
validates :content, presence: true
validates :committee_id, presence: true
validates :category_ids, presence: true



def self.search(search)
  where("title LIKE :search OR content LIKE :search OR id LIKE :search", search: "%#{search}%") 
end


end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]
    skip_before_action :require_login, only: [:index, :show, :categories, :old, :committees]
  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all.order("title ASC")
    @category = Category.all.order("name ASC")
      if params[:search]
        @rules = Rule.search(params[:search]).order("title ASC")
      else
        @rules = Rule.all.order("title ASC")
      end
    valid_rules_only
  end

  def old
    @rules = Rule.all.order("title ASC")
    @rules = Rule.where(title: "Aufräumen")
    @category = Category.all.order("name ASC")
      if params[:search]
        @rules = Rule.search(params[:search]).where('is_valid != ? OR valid_until < ?', true, Date.today).order("title ASC")
      else
        @rules = Rule.where('is_valid != ? OR valid_until < ?', true, Date.today).order("title ASC")
      end
  end
  
  def valid_rules_only
    @rules = @rules.where('is_valid = ?', true) - @rules.where('valid_until < ?', Date.today)
  end
  # GET /rules/1
  # GET /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Regel erstellt.' }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: 'Regel aktualisiert.' }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url, notice: 'Regel gelöscht.' }
      format.json { head :no_content }
    end
  end
  
  def categories
    @category = Category.find(params[:id])
    @rules=Rule.all
      if params[:search]
        @rules = Rule.search(params[:search])
      else
        @rules = Rule.all
      end
    valid_rules_only
    @rules= @rules & Rule.joins(:categories).where(:categories => {id: @category.id})
    
  end
  
  
 def committees
    
    @committee = Committee.find(params[:id])
    
    if params[:search]
        @rules = Rule.search(params[:search]).where(committee_id:@committee.id).order("created_at DESC")
    else
        @rules = Rule.where(committee_id:@committee.id).order('created_at DESC')
    end
    valid_rules_only
    
    
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_params
      params.require(:rule).permit(:is_valid, :title, :content, :created_at, :updated_at, :valid_until, :committee_id, category_ids:[])
    end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<div id="form-container" class="col-m-2">
<%= form_for(@rule) do |f| %>
    <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="col-s-3" id="form-left">
    	

         
  		<div class="form-group">
    		<%= f.label :title %><br>
    		<%= f.text_field :title, {:id => "form-element"} %>
  		</div>
  		<div class="form-group">
    		<%= f.label :content %><br>
    		<%= f.text_area :content, {:id => "form-text-area"}%>
  		</div>

  		


  		
  		<div class="form-group">
  			<%= f.label :Gremium %><br>
   			<%= f.collection_select :committee_id, Committee.all, :id, :name, :include_blank => true%>
        </div>
  		
  		<div class="form-group">
  			<%= f.label :Kategorien %><br>
			<%= collection_select :rule, :category_ids, Category.all, :id, :name, {:selected => @rule.category_ids, :include_blank => false}, {:multiple => true, :size => Category.all.count, :class => 'col_select'} %>
   		</div>
  		<div class="form-group">
    		<%= f.label :Erstellt_am %><br>
    		<%= f.date_select :created_at %>
  		</div>
  		<div class="form-group">
    		<%= f.label :Bearbeitet_am %><br>
    		<%= f.date_select :updated_at, selected: Date.today %>
  		</div>
  		<div class="form-group">
    		<%= f.label :Gültig_bis %><br>
    		<%= f.date_select :valid_until, :include_blank => true %>
  		</div>
  		
  		<div class="form-group">
    		<%= f.label :Gültig %><br>
    		<% if @rule.is_valid==nil%>
    			<%= f.check_box :is_valid, {:checked=>true} %>
    		<% else%>
    			<%= f.check_box :is_valid %>
    		<%end%>
  		</div>
  		
  		<div class="actions">
  		<%= f.submit :Speichern %>
  		</div> 		
    </div>          
  
<% end %>




</div>

app/views/rules/_listrules.html.erb
<% @rules.each do |r|%>

			<div class="row nomargin">
				<div id="element-container" class='col-xs-12'>
				  <div class="row-eq-height nomargin">
				  	
				  	
					<div class="col-sm-3 col-xs-4 nopadding" id="element-left">
						<div id="element-title" class="col-xs-12 padding8 umbruch"> <%= link_to r.title, rule_path(r), method: 'get', :id => "element-title-link" %>  </div>
						<div id="element-text" class="col-xs-12 padding8" style="margin-top:8px;">
							<div class="umbruch">
								
								<div style="margin-bottom:4px;">
									<strong>Gremium:</strong></br> <%= r.committee.name %> </br>
								</div>
							
								<div style="margin-bottom:4px;">
									<% count=r.categories.count %>
									<% i = 1 %>
									<% if r.categories.count==1%><strong>Kategorie:</strong> </br><% elsif r.categories.count==0%><%else%><strong>Kategorien:</strong> </br><%end%>											
									<% r.categories.all.each do |c|%>
										<% if i==count %>
											<%= c.name %>
										<%else%>
											<%= c.name %></br>
											<% i=i+1 %>	
										<% end %>
									<%end%>
								</div>
							
								<div style="margin-bottom:4px;">
									<% if r.valid_until!=nil%> <strong>Gültig bis:</strong> </br> <%= r.valid_until.strftime("%d.%m.%y") %> <%end%>
								</div>
								
							</div>
						</div>
					</div>
					
					<div class="col-sm-9 col-xs-8 nopadding">
						<div id="element-head" class="col-xs-12 umbruch">							
							<div style="float:left;"> Geändert am: <%= r.updated_at.strftime("%d.%m.%y") %>	</div>						
						
							<div style="float:right;">
							<% if logged_in?%>
								<%= link_to 'Bearbeiten', edit_rule_path(r), method: 'get'%>
								<%= link_to 'Löschen', r, method: :delete, data: { confirm: 'Bist du sicher?' }%>
							<%end%>	
							</div>						
						</div>
						
						<div id="element-content" class="col-xs-12 umbruch">
							<%= h(r.content).gsub("\n" , "<br />" ).html_safe%>	
						</div>
						
						
					</div>					
				  </div>
				</div>
			</div>

<%end%>				
					
					
					
					
				
	
				

app/views/rules/_listrules2.html.erb
<% @rules.each do |r|%>
	<%if r.is_valid==true%>
		<% if r.valid_until!=nil and r.valid_until.to_date<Date.today%>
		<% else%>
			<div class="row">
				<div id="element-container" class='col-xs-12'>
				
					
					<div id="element-head-title" class="col-xs-6"> <%= link_to r.title, rule_path(r), method: 'get', :id => "element-title-link" %>  </div>
					<div id="element-head-text" class="col-xs-6"> <%= r.committee.name %>, <%= r.updated_at.strftime("%d.%m.%y") %></div>
					
				
					<div id="element-content" class="col-xs-12"><%= h(r.content).gsub("\n" , "<br />" ).html_safe%>	</div>
				
					
					
						<div id="element-foot-text" class="col-xs-4 left">
							<% count=r.categories.count %>
							<% i = 1 %>
							<% if r.categories.count==1%>Kategorie: <% elsif r.categories.count==0%><%else%>Kategorien: <%end%>											
							<% r.categories.all.each do |c|%>
								<% if i==count %>
									<%= c.name %>
								<%else%>
									<%= c.name %>,
									<% i=i+1 %>	
								<% end %>
							<%end%>	
						</div>
					
						<div id="element-foot-text" class="col-xs-4 center">
						<% if logged_in?%>
						<%= link_to 'Bearbeiten', edit_rule_path(r), method: 'get'%>
						<%= link_to 'Löschen', r, method: :delete, data: { confirm: 'Bist du sicher?' }%>
						<%end%>
						</div>
					
						<div id="element-foot-text" class="col-xs-4 right">
						<% if r.valid_until!=nil%> Gültig bis: <%= r.valid_until.strftime("%d.%m.%y") %> <%end%>
						</div>
					
				</div>
			</div>
		<%end%>
	<%end%>
<%end%>

app/views/rules/categories.html.erb
<div id="list-head">

<% @title= @category.name %>					

<%= form_tag cats_path, :method => 'get' do %>
  <div id="search-form" class="form-group">
    <%= text_field_tag :search, params[:search], {:id => "search-textfield"}  %>
    <%= submit_tag "Suchen", :name => nil, :id => "search-button"  %>
  </div>
<% end %>

</div>
		
		

		
<%= render "listrules" %>

app/views/rules/committees.html.erb
<div id="list-head">
<% @title= @committee.name %>	
			

<%= form_tag coms_path, :method => 'get' do %>
  <div id="search-form" class="form-group">
    <%= text_field_tag :search, params[:search], {:id => "search-textfield"}  %>
    <%= submit_tag "Suchen", :name => nil, :id => "search-button"  %>
  </div>
<% end %>
</div>

		
		

		
<%= render "listrules" %>

app/views/rules/edit.html.erb
<% @title= "Regel bearbeiten" %>	

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/index.html.erb
<div class="row nomargin">	
	<div id="list-head" class="col-xs-12">
		<p id="notice"><%= notice %></p>
		<% @title= "Regelbuch" %>	

		<%= form_tag rules_path, :method => 'get' do %>
  			<div id="search-form" class="form-group">
    			<%= text_field_tag :search, params[:search], {:id => "search-textfield"}  %>
    			<%= submit_tag "Suchen", :name => nil, :id => "search-button"  %>
  			</div>
		<% end %>
	</div>
</div>


<div class="row nomargin">
	<%= render 'listrules'%>
</div>	
			

app/views/rules/new.html.erb
<% @title= "Neue Regel" %>
<%= render 'form' %>

app/views/rules/old.html.erb
<div id="list-head">
<p id="notice"><%= notice %></p>

<% @title= "Inaktive Regeln" %>	

<%= form_tag old_path, :method => 'get' do %>
  <div id="search-form" class="form-group">
    <%= text_field_tag :search, params[:search], {:id => "search-textfield"}  %>
    <%= submit_tag "Suchen", :name => nil, :id => "search-button"  %>
  </div>
<% end %>
</div>

<%= render 'listrules'%>

app/views/rules/show.html.erb
<% @title= @rule.title %>
<% @rules=Rule.where(id:@rule.id)%>
<%= render 'listrules'%>
<div class="bottom-links">
<%= link_to 'Back', :back %>
</div>